seed_everything: 42
trainer:
  default_root_dir: results
  callbacks:
    class_path: Metric
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: results
  accelerator: auto
  auto_select_gpus: true
  devices: 1
