model:
  config: 
    loss: 'CrossEntropyLoss'
    optimizer: 'Adam'
    lr: 0.001
    step_size: 10
    gamma: 0.1
    num_classes: 6
    model:
      in_channels: 1
      out_channels: 6
data:
  data_path: "data"
  train_csv: "results/test.csv"
  val_csv: "results/test.csv"
  test_csv: "results/test.csv"
  batch_size: 2
  num_workers: 4
trainer:
  max_epochs: 2
  accelerator: mps
  precision: 16
  devices: 1
  log_every_n_steps: 10
seed_everything: 42 # Seed for reproducibility
