model:
  config: 
    loss: 'CrossEntropyLoss'
    optimizer: 'Adam'
    lr: 0.001
    step_size: 10
    gamma: 0.1
    num_classes: 6
    model:
      in_channels: 1
      out_channels: 6
      #upsample: 'deconv'
      f_maps: 32
data:
  data_path: "data/128x128x128"
  train_csv: "results/train.csv"
  val_csv: "results/test.csv"
  test_csv: "results/test.csv"
  batch_size: 1
  num_workers: 1
trainer:
  max_epochs: 10
  accelerator: gpu
  precision: bf16-mixed
  strategy: ddp
  devices: 4
  log_every_n_steps: 10
  profiler: pytorch
seed_everything: 42 # Seed for reproducibility
